kind: pipeline
name: default  # Default build routine, releases to Github if tagged

steps:
    - name: build
      image: golang:1.11.9-stretch
      commands:
          - ci/install_gdal.sh
          - go get
          - OUTPUT = dist/{{.Dir}}\_$DRONE_TAG\_{{.OS}}_{{.Arch}}
          - gox -os="linux" -arch="amd64" -output=$OUTPUT
          - ls -al
    - name: publish
      image: plugins/github-release
      settings:
          api_key:
              from_secret: github_token 
          title: Release $DRONE_TAG
          files: dist/*
      when:
          event: tag

---
kind: pipeline
name: release-latest # Latest release to GCS, triggers for tag commits

steps:
    - name: build
      image: karalabe/xgo-latest 
      commands:
          - ci/install_gdal.sh
          - > 
            xgo
            --out tiffany-latest
            --targets=linux/amd64
            -v
            .
          - mkdir dist && mv tiffany* dist/
    - name: release
      image: plugins/gcs
      settings:
          source: dist
          target: tm-tiffany/releases/
          ignore: tiffany.out
          acl: allUsers:READER
          token:
              from_secret: gcs_token
trigger:
    event:
    - tag

---
kind: pipeline
name: release-nightly # Nightly release to GCS, triggers only at master

steps:
    - name: build
      image: karalabe/xgo-latest 
      commands:
          - ci/install_gdal.sh
          - > 
            xgo
            --out tiffany-nightly
            --targets=linux/amd64
            -v
            .
          - mkdir dist && mv tiffany* dist/
    - name: release
      image: plugins/gcs
      settings:
          source: dist
          target: tm-tiffany/releases/
          ignore: tiffany.out
          acl: allUsers:READER
          token:
              from_secret: gcs_token
trigger:
    branch:
    - master
