kind: pipeline
name: default

steps:
    - name: gdal
      image: continuumio/miniconda
      commands:
          - conda install gdal
    - name: build
      image: karalabe/xgo-latest 
      commands:
          - > 
            xgo
            --out tiffany-$DRONE_TAG
            --targets=linux/amd64,linux/386,darwin/*,windows/* 
            -v
            .
