kind: pipeline
name: default  # Default build routine, releases to Github if tagged

steps:
    - name: build
      image: golang:1.11.9-stretch
      commands: 
        - make TAG=$DRONE_TAG build
    - name: publish
      image: plugins/github-release
      settings:
          api_key:
              from_secret: github_token 
          title: Release $DRONE_TAG
          files: dist/*
      when:
          event: tag

---
kind: pipeline
name: release-latest # Latest release to GCS, triggers for tag commits

steps:
    - name: build
      image: golang:1.11.9-stretch
      commands: 
        - make TAG=latest build
    - name: release
      image: plugins/gcs
      settings:
          source: dist
          target: tm-tiffany/releases/
          ignore: tiffany.out
          acl: allUsers:READER
          token:
              from_secret: gcs_token
trigger:
    event:
    - tag

---
kind: pipeline
name: release-nightly # Nightly releases to GCS, triggers only at master

steps:
    - name: build
      image: golang:1.11.9-stretch
      commands: 
        - make TAG=nightly build
    - name: release
      image: plugins/gcs
      settings:
          source: dist
          target: tm-tiffany/releases/
          ignore: tiffany.out
          acl: allUsers:READER
          token:
              from_secret: gcs_token
      when:
          branch:
              - master
          event:
              exclude:
              - pull_request
trigger:
    branch:
    - master
