kind: pipeline
name: build

steps:
    - name: xgo_build
      image: karalabe/xgo-latest
      commands:
          - export TAG=$(git describe --tags)
          - > 
            xgo
            --out tiffany-$TAG
            --targets=linux/amd64,linux/386,darwin/*,windows/* 
            -v
            github.com/thinkingmachines/tiffany
