kind: pipeline
name: default

workspace:
    base: /go
    path: src/github.com/thinkingmachines/tiffany

steps:
    - name: xgo_build
      image: karalabe/xgo-latest
      commands:
          - > 
            xgo
            --out tiffany-$DRONE_TAG
            --targets=linux/amd64,linux/386,darwin/*,windows/* 
            -v
            github.com/thinkingmachines/tiffany
